-- MySQL Script generated by MySQL Workbench
-- Fri Jun 21 15:22:16 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema alura_foro_spring
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema alura_foro_spring
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `alura_foro_spring` DEFAULT CHARACTER SET utf8 ;
USE `alura_foro_spring` ;

-- -----------------------------------------------------
-- Table `alura_foro_spring`.`cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alura_foro_spring`.`cursos` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(200) NULL,
  `categoria` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alura_foro_spring`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alura_foro_spring`.`usuarios` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `email` VARCHAR(150) NULL,
  `password` VARCHAR(300) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alura_foro_spring`.`topicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alura_foro_spring`.`topicos` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(200) NULL,
  `mensaje` VARCHAR(1000) NULL,
  `fecha_creacion` DATETIME NULL,
  `status` VARCHAR(45) NULL,
  `topicos_usuarios_id` BIGINT NOT NULL,
  `topicos_cursos_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`, `topicos_usuarios_id`, `topicos_cursos_id`),
  INDEX `fk_topicos_cursos1_idx` (`topicos_cursos_id` ASC) VISIBLE,
  INDEX `fk_topicos_usuarios1_idx` (`topicos_usuarios_id` ASC) VISIBLE,
  CONSTRAINT `fk_topicos_cursos1`
    FOREIGN KEY (`topicos_cursos_id`)
    REFERENCES `alura_foro_spring`.`cursos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_topicos_usuarios1`
    FOREIGN KEY (`topicos_usuarios_id`)
    REFERENCES `alura_foro_spring`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alura_foro_spring`.`respuestas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alura_foro_spring`.`respuestas` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `mensaje` VARCHAR(1000) NULL,
  `respuestas_topicos_id` BIGINT NOT NULL,
  `fecha_creacion` DATETIME NULL,
  `respuestas_usuarios_id` BIGINT NOT NULL,
  `solucion` VARCHAR(45) NULL,
  PRIMARY KEY (`id`, `respuestas_topicos_id`, `respuestas_usuarios_id`),
  INDEX `fk_respuestas_topicos_idx` (`respuestas_topicos_id` ASC) VISIBLE,
  INDEX `fk_respuestas_usuarios1_idx` (`respuestas_usuarios_id` ASC) VISIBLE,
  CONSTRAINT `fk_respuestas_topicos`
    FOREIGN KEY (`respuestas_topicos_id`)
    REFERENCES `alura_foro_spring`.`topicos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_respuestas_usuarios1`
    FOREIGN KEY (`respuestas_usuarios_id`)
    REFERENCES `alura_foro_spring`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alura_foro_spring`.`perfiles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alura_foro_spring`.`perfiles` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alura_foro_spring`.`usuarios_has_perfiles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alura_foro_spring`.`usuarios_has_perfiles` (
  `usuarios_id` BIGINT NOT NULL,
  `perfiles_id` BIGINT NOT NULL,
  PRIMARY KEY (`usuarios_id`, `perfiles_id`),
  INDEX `fk_usuarios_has_perfiles_perfiles1_idx` (`perfiles_id` ASC) VISIBLE,
  INDEX `fk_usuarios_has_perfiles_usuarios1_idx` (`usuarios_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuarios_has_perfiles_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `alura_foro_spring`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_has_perfiles_perfiles1`
    FOREIGN KEY (`perfiles_id`)
    REFERENCES `alura_foro_spring`.`perfiles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
